# Generated by Django 2.2.8 on 2020-01-15 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
