# Generated by Django 2.2.8 on 2020-01-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(default='c0ZAhA', editable=False, help_text='Job Id', max_length=6, unique=True)),
                ('job_role', models.CharField(help_text='Job roles', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Job role created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Job roles updated date')),
            ],
        ),
    ]
