# Generated by Django 2.2.8 on 2020-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRole',
            fields=[
                ('job_Id', models.CharField(default='dxUwZb', editable=False, max_length=6, primary_key=True, serialize=False)),
                ('job_role', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
