# Generated by Django 2.2.8 on 2020-01-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job_Id',
            field=models.CharField(default='SqIjhY', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
