# Generated by Django 2.2.8 on 2020-01-21 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job_id',
            field=models.CharField(default='23M76b', editable=False, help_text='Job Id', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
