# Generated by Django 2.2.8 on 2020-01-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200117_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job_Id',
            field=models.CharField(default='MjUYTe', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
