# Generated by Django 2.2.8 on 2020-01-21 13:59

import access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_auto_20200121_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrole',
            name='job_id',
            field=models.CharField(default=access.models.jobId, editable=False, help_text='Job Id', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='job_role',
            field=models.CharField(default='', help_text='Job roles', max_length=50),
            preserve_default=False,
        ),
    ]
